/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CL */

#ifndef _Included_CL
#define _Included_CL
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     CL
 * Method:    makeClass
 * Signature: (Ljava/lang/String;[B)Ljava/lang/Class;
 */
  JNIEXPORT jclass JNICALL Java_cn_web1992_cl_CL_makeClass(JNIEnv *, jobject, jstring, jbyteArray);

  /*
 * Class:     CL
 * Method:    DisplayHello
 * Signature: ()V
 */
  JNIEXPORT void JNICALL Java_cn_web1992_cl_CL_DisplayHello(JNIEnv *, jobject);

  /*
 * Class:     cn_web1992_cl_CL
 * Method:    encByte
 * Signature: ([B)[B
 */
  JNIEXPORT jbyteArray JNICALL Java_cn_web1992_cl_CL_encByte(JNIEnv *, jobject, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
