/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_springframework_asm_ClassReader */

#ifndef _Included_org_springframework_asm_ClassReader
#define _Included_org_springframework_asm_ClassReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_springframework_asm_ClassReader
 * Method:    encByte
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_springframework_asm_ClassReader_encByte
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
